# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70f2f92a6db41b32063add3cf463aa634c4be7653b85bbea2d43063ca3cca82a6ec8777d1ca78b43d8bdd19ac9e2669320b11d055b6b875a72ff5791ae5bbc09

test:
  secret_key_base: ffd30b1a8e2cc699092dea8304967c8da142c20257ca4d2e06973a2e6b811f69599faab2bb2e25140202a3a99e9953b241df24654f3d1e14d12d4b2cf56653ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
